name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 1 UTC everyday
    - cron: "0 1 * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          IMG_ALT: Image ALT
          GH_TOKEN: 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
          #README_REPOSITORY: <username>/<differentrepo> # No need to mention this if workflow present in current non profile repo.
